ESP32Async/ESPAsyncWebServer

.github/workflows/ci.yml
README.md
platformio.ini
src/ESPAsyncWebServer.h
src/WebResponseImpl.h
src/WebResponses.cpp

`-D ASYNCWEBSERVER_USE_CHUNK_INFLIGHT=0` will disable inflight code in chunk responses and allow smaller chunk buffers to be used with higher number of concurrent chunk requests in the case of dat serving from (faster than sdcard) flash memory for example.
See: https://github.com/ESP32Async/ESPAsyncWebServer/issues/4

Introduce -D ASYNCWEBSERVER_USE_CHUNK_INFLIGHT=0|1 to be able to enabled/disable inflight in chunk response

---

src/AsyncWebSocket.cpp

In relation to https://github.com/ESP32Async/ESPAsyncWebServer/pull/29 and https://github.com/ESP32Async/ESPAsyncWebServer/issues/28, I also found similar issue in WebSocket client cleanup code

fix(ws): break loop after erasing client

---

examples/CaptivePortal/CaptivePortal.ino
examples/Filters/Filters.ino
examples/Issue162/Issue162.ino
examples/Issue85/Issue85.ino
examples/SSE_perftest/SSE_perftest.ino
examples/SimpleServer/SimpleServer.ino
examples/StreamFiles/StreamConcat.h
examples/StreamFiles/StreamFiles.ino
src/AsyncEventSource.cpp
src/AsyncEventSource.h
src/AsyncJson.cpp
src/AsyncJson.h
src/AsyncMessagePack.cpp
src/AsyncMessagePack.h
src/AsyncWebHeader.cpp
src/AsyncWebSocket.cpp
src/AsyncWebSocket.h
src/ChunkPrint.cpp
src/ChunkPrint.h
src/ESPAsyncWebServer.h
src/Middleware.cpp
src/WebAuthentication.cpp
src/WebAuthentication.h
src/WebHandlerImpl.h
src/WebHandlers.cpp
src/WebRequest.cpp
src/WebResponseImpl.h
src/WebResponses.cpp
src/WebServer.cpp
src/literals.h

(also same pr in asynctcp https://github.com/ESP32Async/AsyncTCP/pull/4)
The project is under LGPL license so the source files should reflect that by having a license header compliant with LGPL, or at least have an appropriate SPDX header.
This changed is required to allow the source files to be used in downstream project because some files are not licensed in accordance to the LPGL rules.
Refs:
- https://www.gnu.org/licenses/gpl-howto.html
- https://spdx.dev/learn/handling-license-info/
- https://spdx.org/licenses/LGPL-3.0-or-later.html

Update license headers

---

.github/scripts/update-version.sh
README.md

```bash
~/.../me/ESPAsyncWebServer ( ci/update-version.sh {3} S:2 U:4 ⊘ )
❯  .github/scripts/update-version.sh 4 5 6
New AsyncTCP version: 4.5.6
Updating library.properties...
Updating library.json...
Updating src/AsyncWebServerVersion.h...
```

(ci): Add update-version.sh script to prepare a next release

---

src/WebHandlers.cpp

Just run:
`http://192.168.4.1/foo`
When `/foo` does not exist and no notFoundHalder is defined to reproduce the issue.

fix(http): Status 404 should be returned by default when no notFoundHandler is set. This is not an internal server error.

---

README.md
examples/Headers/Headers.ino
src/ESPAsyncWebServer.h
src/WebResponses.cpp
src/literals.h

There are some exceptions that are always allowed only once.
Fixes: https://github.com/ESP32Async/ESPAsyncWebServer/issues/47

Add the option to add multiple headers with the same name

---

examples/SkipServerMiddleware/SkipServerMiddleware.ino
platformio.ini
src/ESPAsyncWebServer.h
src/WebRequest.cpp
src/WebServer.cpp

- Allow to skip global server middleware on any handler
- Allow to access the catch-all handler to add middlewares on it
Solves: https://github.com/ESP32Async/ESPAsyncWebServer/discussions/49
I added an example showing how to use that: https://github.com/ESP32Async/ESPAsyncWebServer/blob/feat/skip-server-middleware/examples/SkipServerMiddleware/SkipServerMiddleware.ino
```c++
// we apply auth middleware to the server globally
server.addMiddleware(&basicAuth);
// protected endpoint: requires basic authentication
// curl -v -u admin:admin  http://192.168.4.1/
server.on("/", HTTP_GET, [](AsyncWebServerRequest *request) {
request->send(200, "text/plain", "Hello, world!");
});
// we skip all global middleware from the catchall handler
server.catchAllHandler().skipServerMiddlewares();
// we …
```

feat(http): Skipping Middleware

---

src/ESPAsyncWebServer.h
src/WebRequest.cpp

This PR allows the user to abort a request.
Tested that with autocannon, 16 or 48 // workerrs, works fine.
The idea is to provide the capability to the user (and us also) to reset the connection in case something has to be stopped now, i.e. bad allocation.
Currently, the use had to do: `request->client()->abort()` which is wrong because out of the scope of the request object (_sent and _paused flags should be correctly handled)

feat(http): Add ability to abort a request

---

pioarduino_examples/IncreaseMaxSockets/.gitignore
pioarduino_examples/IncreaseMaxSockets/platformio.ini
pioarduino_examples/IncreaseMaxSockets/src/main.cpp

This examples show how to use pioarduino hybrid compilation to increased the # of sockets and also increase the asynctcp queue size.
Example driven from _Dr.Random_'s request

doc(example): pioarduino example with hybrid compilation to show how to increase the max sockets (CONFIG_LWIP_MAX_ACTIVE_TCP)

---

src/WebRequest.cpp

When accepting an upload, discard any bytes after Content-Length.  This ensures that handlers such as AsyncJson can safely allocate the correct sized buffer without needing to additionally check for overrun.
Fixes #100

Discard bytes after Content-Length

---

.github/workflows/build-arduino.yml
README.md
library.json
platformio.ini
src/AsyncEventSource.h
src/WebHandlers.cpp

- Support for Arduino Pico SDK v4.4.4
- Set CLI to point to latest arduino-pico SDK

Fix: Arduino Pico SDK v4.4.4

---

examples/WebSocketEasy/WebSocketEasy.ino
platformio.ini
src/AsyncWebSocket.h

This PR is a proposal to add an easier to use WebSocket handler for unfragmented messages, which is 90% of the use cases. The current WebSocket API is complex to use, I think this one will help a lot.

Added an easy to use WebSocket handler AsyncWebSocketMessageHandler with an example

---

examples/AsyncResponseStream/AsyncResponseStream.ino
platformio.ini
src/WebResponseImpl.h
src/WebResponses.cpp

This PR fixes an issue discovered in OpenDTU (see: https://github.com/tbnobody/OpenDTU/issues/2535).
The replacement of cbuf by StringStream is definitely slower (3-4 times). Even calling `setTimeout(0)` to inhibit the timed read with `readBytes()` does not help speeding up.
This PR reverts the code and also provides a MRE helping isolate the problem / reproduce it.
The use of `StringStream ` was causing several issues like:
- throttling within slow response (poll events)
- TWDT could trigger because of the slow StringStream
**Note: this issue is only visible for big payloads: this OpenDTU endpoints uses a buffer of 40k.**

Reverted AsyncResponseStream buffer to cbuf which is considerably faster than StreamString

---

examples/WebSocket/WebSocket.ino
src/AsyncWebSocket.cpp
src/AsyncWebSocket.h

- Handle client disconnection event properly even if cleanupClients is not called within the main loop.
- Avoid self-deadlock by using recursive mutex.

Fix WebSocket

---

src/AsyncWebHeader.cpp

- Fix https://github.com/ESP32Async/ESPAsyncWebServer/security/advisories/GHSA-87j8-6f7g-h8wh

Fix CRLF Injection in AsyncWebHeader.cpp (GHSA-87j8-6f7g-h8wh)

---

src/AsyncEventSource.h
src/AsyncWebSocket.h

chrono:360:47: error: macro "round" passed 2 arguments, but takes just 1

Fix compile on libretiny due to round macro conflict

---

src/AsyncWebServerRequest.cpp
src/ESPAsyncWebServer.h
src/WebResponses.cpp

This PR brings improved standards-compliant handling of pre-compressed .gz files, providing ETag support and conditional responses, helping optimize client-side caching and server resource usage. Fully backward compatible.
ETag Generation for Pre-compressed .gz Files
When a .gz file is served via AsyncFileResponse, the server now generates an ETag header based on the CRC32 checksum found ((first 4 bytes) in the gzip trailer (last 8 bytes of gz file).
A Cache-Control: no-cache header is also added to enforce proper cache validation.
Conditional Request Support in send()
The send() method now checks for the If-None-Match header when a .gz version of the requested file exists.
If the client's ETag matches the server's ETag (derived from the gzip trailer), the server responds with 304 Not …

 ETag and caching for serving pre‐compressed files

---

src/WebRequest.cpp

The value is checked here to be different from zero:
https://github.com/ESP32Async/ESPAsyncWebServer/blob/28039890683ce40a12de4e02343404f9ee6a2ecc/src/WebRequest.cpp#L266-L268
To have a defined behavior I would recommend to set `_onDisconnectfn` to `NULL`

set default value for '_onDisconnectfn'

---

src/AsyncWebHeader.cpp

This patch makes the usage of strchr() return value slightly more strict by using const. This doesn't change any functionality but allows the code to be compiled in environments where we are forced to use C++ standard-compliant versions of strchr (that don't return char* when const char* is given).
This change also makes the code a bit safer and correct since the pointers in question are derived from a const char* data-parameter that was never meant for modification any way.

Use const return value with strchr

---

src/WebResponses.cpp

This patch removes an implementation of memchr() that seems unnecessary. The standard library even for ESP8266 provide this implementation in recent releases. Removal is preferred when source code is compiled with standard library that define the function as inline.

Remove unnecessary implementation of memchr

---

src/WebResponses.cpp
src/literals.h

This refactor improves AsyncFileResponse::AsyncFileResponse(File content, const String &path, const char *contentType, bool download, AwsTemplateProcessor callback) The updated implementation:
- Replaces the use of String::endsWith() with a more efficient memcmp() check for gzip file suffix.
- Fix the download of precompresed archives. The old behavior was wrong.
- Simplifies content-disposition header generation using consistent logic for both inline and download cases.
Overall, the refactor enhances performance slightly and ensures more consistent behavior when serving compressed downloadable files.

refactor: optimize AsyncFileResponse handling

---

src/ESPAsyncWebServer.h
src/Middleware.cpp

When credential flag is set to true, origin cannot be set to * (browser contraint).
So we mimic the same behavior by answering back in `Access-Control-Allow-Origin` header the `Origin `value, but only if the user set origin to * in the CORS middleware settings.
Ref: https://github.com/ESP32Async/ESPAsyncWebServer/issues/294
Fix #294.

Fix CORS behavior when credentials flag is set to true.

---

examples/Templates/Templates.ino
src/ESPAsyncWebServer.h
src/WebHandlers.cpp
src/literals.h

This PR updates AsyncStaticWebHandler::handleRequest to correctly manage caching headers when template processing introduces dynamic content. The previous implementation always set ETag and Last-Modified headers based on the underlying filesystem metadata, which was misleading when templates generated non-static responses (e.g., current time). Issue #237
The new implementation:
- Uses file-based ETag when .gz files or template callback is not present.
- Ensures gzip files generate consistent ETag values using _getEtag.
- For non-gzip files, generate ETag values ​​using the timestamp or file size.
- Returns 304 Not Modified only when If-None-Match matches the valid ETag.
- Removed use of Variable Length Array and String, ensuring the same implementation works consistently on all platforms. …

Fix ETag handling for dynamic template responses

---

src/WebHandlers.cpp

```
src/WebHandlers.cpp: In member function 'virtual void AsyncStaticWebHandler::handleRequest(AsyncWebServerRequest*)':
src/WebHandlers.cpp:237:38: warning: format '%x' expects argument of type 'unsigned int', but argument 4 has type 'uint32_t' {aka 'long unsigned int'} [-Wformat=]
237 |     snprintf(etag, sizeof(etag), "%08x", etagValue);
|                                   ~~~^   ~~~~~~~~~
|                                      |   |
|                                      |   uint32_t {aka long unsigned int}
|                                      unsigned int
|                                   %08lx
```

Fix compiler warning
